# Site settings
name: Hung Q. Ngo's Homepage
description: > # this means to ignore newlines until "baseurl:"
    This is Hung Q. Ngo's personal homepage.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cse.buffalo.edu/~hungngo" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
